# Generated by Django 5.1.7 on 2025-04-07 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chatroom_is_favourite_chatroom_is_pinned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('is_typing', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='group_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
